### ISSUE TITLE
0.4.1 broke eslint

### ISSUE THREAD

**Issue by digitalkaoz** [yavorskiy/comment-parser#36] opened 2017-09-19 15:49 UTC
see https://github.com/gajus/eslint-plugin-jsdoc/issues/41

i guess nearly the whole world using eslint is affected by this bug...

**Comment by SergeAstapov** [comment] 2017-09-19 18:49
Got same problem today in our CI.

**Comment by yavorskiy** [comment] 2017-09-19 23:10
will dig into this tonight and try to solve

**Comment by SergeAstapov** [comment] 2017-09-21 23:17
Seems an issues is caused by incorrect parsing of indented JSDoc blocks.

Test input:
```
# reproduction.js
const parse = require('comment-parser');
const input = `/**
     * Invoke showLoader action.
     * Bound to controller instance so can be used as callback.
     *
     * @example
     * resourceManager.getSomeObject().then(this.showLoader)
     * @protected
     * @see ApplicationRoute.actions.showLoader`
     */`
console.dir(parse(input3), { depth: 3 });
```

```
npm install comment-parser@0.3
node ./repro.js
comment-parser-reproduction sastapov$ node ./repro.js
```
emits
```
[]
```

Then installing version `0.4.1` results in
```
comment-parser-reproduction sastapov$ npm install comment-parser@0.4
comment-parser-reproduction@1.0.0 /Users/sastapov/Code/tmp/comment-parser-reproduction
└── comment-parser@0.4.1

npm WARN comment-parser-reproduction@1.0.0 No description
npm WARN comment-parser-reproduction@1.0.0 No repository field.
comment-parser-reproduction sastapov$ node ./repro.js
[ { tags: [],
    line: 0,
    description: '* Invoke showLoader action.\n* Bound to controller instance so can be used as callback.\n*\n* @example\n* resourceManager.getSomeObject().then(this.showLoader)\n* @protected\n* @see ApplicationRoute.actions.showLoader',
    source: '* Invoke showLoader action.\n* Bound to controller instance so can be used as callback.\n*\n* @example\n* resourceManager.getSomeObject().then(this.showLoader)\n* @protected\n* @see ApplicationRoute.actions.showLoader' } ]
comment-parser-reproduction sastapov$
```

**Comment by SergeAstapov** [comment] 2017-09-22 00:08
Seems that incorrect usage of `comment-parser` as it allows to have indented comments by `eslint-plugin-jsdoc`.
Following comment is parsed as expected:
```
        /**
         * Invoke showLoader action.
         * Bound to controller instance so can be used as callback.
         *
         * @example
         * resourceManager.getSomeObject().then(this.showLoader)
         * @protected
         * @see ApplicationRoute.actions.showLoader
         */
```
whereas `eslint-plugin-jsdoc` pass comment string as:
```
const input = `/**
         * Invoke showLoader action.
         * Bound to controller instance so can be used as callback.
         *
         * @example
         * resourceManager.getSomeObject().then(this.showLoader)
         * @protected
         * @see ApplicationRoute.actions.showLoader
         */`;
```
which is not handled properly.

 This behavior has been changed between v0.3.2 and v0.4.1 which broke `eslint-plugin-jsdoc`.

**Comment by yavorskiy** [comment] 2017-09-23 05:30
@SergeAstapov I see, 0.4.1 is not using `*` as the line start marker but calculating it based on opening `/**` segment position, so this snippet
```
const input = `/**
     * Invoke showLoader action.
     * Bound to controller instance so can be used as callback.
     *
     * @example
     * resourceManager.getSomeObject().then(this.showLoader)
     * @protected
     * @see ApplicationRoute.actions.showLoader`
     */`
```
reads as
```
const input = `/**
                  Loader action.
                  ntroller instance so can be used as callback.

     
                  nager.getSomeObject().then(this.showLoader)

                  ationRoute.actions.showLoader`
```

I apologize for introducing this, working on the fix. For now the workaround would be reverting to `0.3.2`

**Comment by brokentone** [comment] 2017-09-23 16:03
@yavorskiy This logic branch fixes this same issue for me.

Correctly parsing comments / reporting on eslint-plugin-jsdoc:
comment-parser@0.4.0 
comment-parser@issue-36

Incorrectly parsing comments:
comment-parser@0.4.1

Since `eslint-plugin-jsdoc` is using `^0.4.0`, if this is published at 0.4.2, you'll fix the whole ecosystem!

**Comment by yavorskiy** [comment] 2017-09-24 00:27
@brokentone awesome, thanks for your feedback

**Comment by yavorskiy** [comment] 2017-09-24 00:29
`comment-parser@0.4.2` is out.
 anybody pls confirm `eslint-plugin-jsdoc` is good with it

**Comment by SergeAstapov** [comment] 2017-09-24 02:27
@yavorskiy `eslint-plugin-jsdoc` was fixed by correct usage of `comment-parser` package - fix was to preserve JSDoc block start/end indentation (please see https://github.com/gajus/eslint-plugin-jsdoc/pull/42/files)

Anyway version v0.4.2 works good for various use cases! Thanks for the fix!

**Closed** 2017-09-24 03:30 UTC
